version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: a_kop
      POSTGRES_USER: root_dev
      POSTGRES_PASSWORD: root_dev
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: test@example.com
      PGADMIN_DEFAULT_PASSWORD: root_dev
    ports:
      - "5050:80"
    depends_on:
      - db

  app:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    image: app
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
        DB_CONNECTION: pgsql
        DB_HOST: db
        DB_PORT: 5432
        DB_DATABASE: a_kop
        DB_USERNAME: root_dev
        DB_PASSWORD: root_dev